# Generated by Django 3.1.13 on 2021-10-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='net',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
