# Generated by Django 3.1.13 on 2021-10-21 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('listings', '0003_auto_20211018_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='users_fav',
            field=models.ManyToManyField(blank=True, related_name='products_fav', to=settings.AUTH_USER_MODEL),
        ),
    ]
